Repository depromeet/WalWal-iOS, pull requests merged in 2024-09, with the labels that each got.

#250 피드, 다른 사람 프로필 QA 사항 반영
  WalWal/DesignSystem/DemoApp/Sources/WalWalFeed/WalWalFeedViewController.swift
  WalWal/DesignSystem/Sources/Extensions/UILabel+.swift
  WalWal/DesignSystem/Sources/WalWalFeed/Component/FeedHeaderView.swift
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCell.swift
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCellView.swift
  WalWal/DesignSystem/Sources/WalWalFeed/WalWalFeed.swift
  WalWal/DesignSystem/Sources/WalWalProfileCardView/WalWalProfileCardView.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Views/MyPageViewImp.swift
  WalWal/Utility/Sources/String+.swift
Labels: QA

#251 데이터 로드 시 스플래시 이미지 비율 오류 수정
  WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
Labels: HotFix

#256 알림 리스트 없을 경우 엣지페이지 보여주기
  WalWal/Features/FCM/FCMPresenter/Implement/Reactors/FCMReactorImp.swift
  WalWal/Features/FCM/FCMPresenter/Implement/Views/Components/FCMEdgeView.swift
  WalWal/Features/FCM/FCMPresenter/Implement/Views/FCMViewImp.swift
  WalWal/Features/FCM/FCMPresenter/Interface/Reactors/FCMReactor.swift
Labels: 구현

#253 푸시 알림 앱 진입
  WalWal/App/Sources/AppDelegate.swift
  WalWal/App/Sources/AppDependency.swift
  WalWal/Coordinators/App/AppCoordinator/Implement/AppCoordinatorImp.swift
  WalWal/Coordinators/App/AppCoordinator/Interface/AppCoordinator.swift
  WalWal/Coordinators/Feed/FeedCoordinator/Implement/FeedCoordinatorImp.swift
  WalWal/Coordinators/WalWalTabBar/WalWalTabBarCoordinator/Implement/WalWalTabBarCoordinatorImp.swift
  WalWal/DependencyFactory/Feed/FeedDependencyFactory/Implement/FeedDependencyFactoryImp.swift
  WalWal/DependencyFactory/Feed/FeedDependencyFactory/Interface/FeedDependencyFactory.swift
  WalWal/DependencyFactory/Splash/SplashDependencyFactory/Implement/SplashDependencyFactoryImp.swift
  WalWal/DependencyFactory/Splash/SplashDependencyFactory/Interface/SplashDependencyFactory.swift
  WalWal/DependencyFactory/WalWalTabBar/WalWalTabBarDependencyFactory/Implement/WalWalTabBarDependencyFactoryImp.swift
  WalWal/DependencyFactory/WalWalTabBar/WalWalTabBarDependencyFactory/Interface/WalWalTabBarDependencyFactory.swift
  WalWal/Features/Feed/FeedDomain/Implement/RemoveGlobalRecordIdUseCaseImp.swift
  WalWal/Features/Feed/FeedDomain/Interface/RemoveGlobalRecordIdUseCase.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/FeedReactor.swift
  WalWal/Features/Splash/SplashPresenter/Implement/Reactors/SplashReactorImp.swift
Labels: 구현

#260 딥링크 처리 오류 수정
  WalWal/App/Sources/AppDelegate.swift
  WalWal/Coordinators/WalWalTabBar/WalWalTabBarCoordinator/Implement/WalWalTabBarCoordinatorImp.swift
  WalWal/LocalStorage/Sources/UserDefaults.swift
Labels: HotFix

#261 회원가입 오류 수정
  WalWal/Features/Onboarding/OnboardingPresenter/Implement/Views/OnboardingProfileViewImp.swift
Labels: HotFix

#263 부스트 버그 수정
  WalWal/DesignSystem/Sources/WalWalFeed/BoostAnimations/WalWalBoostCounter.swift
  WalWal/DesignSystem/Sources/WalWalFeed/BoostAnimations/WalWalBoostGenerator.swift
  WalWal/DesignSystem/Sources/WalWalFeed/WalWalFeed.swift
Labels: HotFix

#264 스와이프 뒤로가기 구현
  WalWal/Coordinators/Base/BaseCoordinator/Sources/BaseCoordinator.swift
  WalWal/Coordinators/MissionUpload/MissionUploadCoordinator/Implement/MissionUploadCoordinatorImp.swift
  WalWal/Coordinators/MyPage/MyPageCoordinator/Implement/MyPageCoordinatorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/ProfileEditReactorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/ProfileSettingReactorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/RecordDetailReactorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingViewImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Views/RecordDetailViewImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Interface/Reactors/ProfileSettingReactor.swift
  WalWal/Features/MyPage/MyPagePresenter/Interface/Reactors/RecordDetailReactor.swift
Labels: 구현

#267 앱스토어 리뷰 팝업 구현
  WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
  WalWal/Utility/Sources/StoreReviewManager.swift
Labels: 구현
