Repository depromeet/WalWal-iOS, pull requests merged in 2024-10, with the labels that each got.

#274 feat: #273 더블 탭으로 최상단 이동 구현
  WalWal/Coordinators/FCM/FCMCoordinator/Implement/FCMCoordinatorImp.swift
  WalWal/Coordinators/FCM/FCMCoordinator/Interface/FCMCoordinator.swift
  WalWal/Coordinators/Feed/FeedCoordinator/Implement/FeedCoordinatorImp.swift
  WalWal/Coordinators/Feed/FeedCoordinator/Interface/FeedCoordinator.swift
  WalWal/Coordinators/WalWalTabBar/WalWalTabBarCoordinator/Implement/WalWalTabBarCoordinatorImp.swift
  WalWal/DesignSystem/Sources/WalWalTabBarViewController/Component/TabBarItemView.swift
  WalWal/DesignSystem/Sources/WalWalTabBarViewController/WalWalTabBarViewController.swift
  WalWal/Features/FCM/FCMPresenter/Implement/Reactors/FCMReactorImp.swift
  WalWal/Features/FCM/FCMPresenter/Implement/Views/FCMViewImp.swift
  WalWal/Features/FCM/FCMPresenter/Interface/Reactors/FCMReactor.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/FeedViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/FeedReactor.swift
Labels: 구현

#278 피드/기록 셀에 댓글 추가 및 레이아웃 변경
  WalWal/DesignSystem/Sources/Extensions/UILabel+.swift
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCellView.swift
  WalWal/DesignSystem/Sources/WalWalFeed/WalWalFeed.swift
  WalWal/DesignSystem/Sources/WalWalFeed/WalWalFeedModel.swift
  WalWal/Features/Feed/FeedData/Interface/DTO/FeedDTO.swift
  WalWal/Features/Feed/FeedDomain/Interface/Model/FeedListModel.swift
  WalWal/Features/Feed/FeedDomain/Interface/Model/FeedModel.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/RecordDetailReactorImp.swift
  WalWal/GlobalState/Sources/GlobalModels/GlobalFeedListModel.swift
  WalWal/ResourceKit/Resources/Assets.xcassets/Feed/Contents.json
  WalWal/ResourceKit/Resources/Assets.xcassets/Feed/Fire.imageset/Contents.json
  WalWal/ResourceKit/Resources/Assets.xcassets/Feed/Fire.imageset/Fire.png
  WalWal/ResourceKit/Resources/Assets.xcassets/Feed/Fire.imageset/Fire@2x.png
  WalWal/ResourceKit/Resources/Assets.xcassets/Feed/Fire.imageset/Fire@3x.png
  WalWal/ResourceKit/Resources/Assets.xcassets/Feed/Message circle.imageset/Contents.json
  WalWal/ResourceKit/Resources/Assets.xcassets/Feed/Message circle.imageset/Message circle.png
  WalWal/ResourceKit/Resources/Assets.xcassets/Feed/Message circle.imageset/Message circle@2x.png
  WalWal/ResourceKit/Resources/Assets.xcassets/Feed/Message circle.imageset/Message circle@3x.png
  WalWal/ResourceKit/Sources/Font.swift
Labels: 구현

#279 미션 완료 시 미션 탭 카드뷰 추가
  WalWal/DesignSystem/Sources/UnderlinedTextView/UnderlinedTextView.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/Cell/RecordCarouselCell.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/MissionCompleteView.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
  WalWal/Features/Records/RecordsData/Implement/Endpoint/RecordEndpoint.swift
  WalWal/Features/Records/RecordsData/Implement/Parameters/FetchRecordsQuery.swift
  WalWal/Features/Records/RecordsData/Implement/Repository/RecordRepositoryImp.swift
  WalWal/Features/Records/RecordsData/Interface/DTO/CompletedRecordDTO.swift
  WalWal/Features/Records/RecordsData/Interface/DTO/MissionRecordStatusDTO.swift
  WalWal/Features/Records/RecordsData/Interface/Repository/RecordRepository.swift
  WalWal/Features/Records/RecordsDomain/Implement/CheckRecordStatusUseCaseImp.swift
  WalWal/Features/Records/RecordsDomain/Interface/Model/MissionRecordStatusModel.swift
Labels: 구현

#280 신고하기 구현
  WalWal/Coordinators/Feed/FeedCoordinator/Implement/FeedCoordinatorImp.swift
  WalWal/Coordinators/Feed/FeedCoordinator/Interface/FeedCoordinator.swift
  WalWal/DependencyFactory/Feed/FeedDependencyFactory/Implement/FeedDependencyFactoryImp.swift
  WalWal/DependencyFactory/Feed/FeedDependencyFactory/Interface/FeedDependencyFactory.swift
  WalWal/DesignSystem/Sources/CustomTextView/CustomTextView.swift
  WalWal/DesignSystem/Sources/WalWalAlert/WalWalAlert.swift
  WalWal/DesignSystem/Sources/WalWalButton/WalWalButton/WalWalButton.swift
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCell.swift
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCellView.swift
  WalWal/DesignSystem/Sources/WalWalFeed/WalWalFeed.swift
  WalWal/Features/Feed/FeedData/Implement/Endpoint/FeedEndpoint.swift
  WalWal/Features/Feed/FeedData/Implement/Parameters/ReportParameter.swift
  WalWal/Features/Feed/FeedData/Implement/Repository/ReportRepositoryImp.swift
  WalWal/Features/Feed/FeedData/Interface/Repository/ReportRepository.swift
  WalWal/Features/Feed/FeedDomain/Implement/ReportUseCaseImp.swift
  WalWal/Features/Feed/FeedDomain/Interface/ReportUseCase.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedMenuReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/ReportReactor/ReportDetailReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/ReportReactor/ReportTypeReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/Components/FeedMenuListView.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/Components/ReportTextView.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/Components/ReportTypeCell.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/FeedMenuViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/FeedViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/ReportView/ReportDetailViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/ReportView/ReportTypeViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/FeedMenuReactor.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/FeedReactor.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/ReportReactor/ReportDetailReactor.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/ReportReactor/ReportType.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/ReportReactor/ReportTypeReactor.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Views/FeedMenuView.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Views/ReportView/ReportDetailView.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Views/ReportView/ReportTypeView.swift
  WalWal/ResourceKit/Resources/Images.xcassets/chevronRight.imageset/Back.png
  WalWal/ResourceKit/Resources/Images.xcassets/chevronRight.imageset/Back@2x.png
  WalWal/ResourceKit/Resources/Images.xcassets/chevronRight.imageset/Back@3x.png
  WalWal/ResourceKit/Resources/Images.xcassets/chevronRight.imageset/Contents.json
  WalWal/ResourceKit/Resources/Images.xcassets/menu.imageset/Contents.json
  WalWal/ResourceKit/Resources/Images.xcassets/menu.imageset/Meatballs_menu.png
  WalWal/ResourceKit/Resources/Images.xcassets/menu.imageset/Meatballs_menu@2x.png
  WalWal/ResourceKit/Resources/Images.xcassets/menu.imageset/Meatballs_menu@3x.png
  WalWal/ResourceKit/Resources/Images.xcassets/reportIcon.imageset/Contents.json
  WalWal/ResourceKit/Resources/Images.xcassets/reportIcon.imageset/Error.png
  WalWal/ResourceKit/Resources/Images.xcassets/reportIcon.imageset/Error@2x.png
  WalWal/ResourceKit/Resources/Images.xcassets/reportIcon.imageset/Error@3x.png
Labels: 구현

#283 이미지 다운샘플링 및 메모리 관리
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCell.swift
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCellView.swift
  WalWal/DesignSystem/Sources/WalWalFeed/WalWalFeed.swift
  WalWal/Features/FCM/FCMDomain/Interface/Model/FCMListModel.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/FeedViewImp.swift
  WalWal/Features/Members/MembersDomain/Interface/Model/MemberInfo.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/Cell/RecordCarouselCell.swift
  WalWal/Features/MyPage/MyPageDomain/Interface/Model/MemberModel.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/MyPageReactorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/RecordDetailReactorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Views/RecordDetailViewImp.swift
  WalWal/GlobalState/Sources/GlobalState.swift
  WalWal/Utility/Sources/KF+.swift
Labels: 리팩토링, HotFix

#284 댓글 입력 박스 구현
  WalWal/DesignSystem/Sources/CustomInputBox/CustomInputBox.swift
  WalWal/Features/Comment/CommentPresenter/DemoApp/Sources/CommentDemoAppDelegate.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/CommentViewImp.swift
  WalWal/ResourceKit/Resources/Images.xcassets/postIcon.imageset/Contents.json
  WalWal/ResourceKit/Resources/Images.xcassets/postIcon.imageset/Group 2085665735.png
  WalWal/ResourceKit/Resources/Images.xcassets/postIcon.imageset/Group 2085665735@2x.png
  WalWal/ResourceKit/Resources/Images.xcassets/postIcon.imageset/Group 2085665735@3x.png
Labels: HotFix

#290 얼럿 이벤트 처리 이슈 수정
  WalWal/Features/Splash/SplashPresenter/Implement/Views/SplashViewImp.swift
  WalWal/Utility/Sources/AppUpdataManager.swift
Labels: HotFix

#289 댓글 기본 이미지 추가
  WalWal/Features/Comment/CommentPresenter/Implement/Views/Cells/CommentCell.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/Cells/ReplyCommentCell.swift
Labels: HotFix

#293 기록 상세 댓글 연결
  WalWal/Coordinators/MyPage/MyPageCoordinator/Implement/MyPageCoordinatorImp.swift
  WalWal/Coordinators/MyPage/MyPageCoordinator/Interface/MyPageCoordinator.swift
  WalWal/Coordinators/WalWalTabBar/WalWalTabBarCoordinator/Implement/WalWalTabBarCoordinatorImp.swift
  WalWal/DependencyFactory/MyPage/MyPageDependencyFactory/Implement/MyPageDependencyFactoryImp.swift
  WalWal/DependencyFactory/MyPage/MyPageDependencyFactory/Interface/MyPageDependencyFactory.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/RecordDetailReactorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Views/RecordDetailViewImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Interface/Reactors/RecordDetailReactor.swift
Labels: 구현

#295 댓글 레이아웃 수정
  WalWal/DesignSystem/Sources/CustomInputBox/CustomInputBox.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/Cells/CommentCell.swift
Labels: HotFix

#298 피드셀에 댓글 개수 업데이트
  WalWal/Coordinators/Comment/CommentCoordinator/Implement/CommentCoordinatorImp.swift
  WalWal/Coordinators/Comment/CommentCoordinator/Interface/CommentCoordinator.swift
  WalWal/Coordinators/Comment/CommentCoordinator/Project.swift
  WalWal/Coordinators/Feed/FeedCoordinator/Implement/FeedCoordinatorImp.swift
  WalWal/Coordinators/MyPage/MyPageCoordinator/Implement/MyPageCoordinatorImp.swift
  WalWal/DependencyFactory/Comment/CommentDependencyFactory/Implement/CommentDependencyFactoryImp.swift
  WalWal/DependencyFactory/Comment/CommentDependencyFactory/Interface/CommentDependencyFactory.swift
  WalWal/DependencyFactory/Comment/CommentDependencyFactory/Project.swift
  WalWal/DependencyFactory/Feed/FeedDependencyFactory/Implement/FeedDependencyFactoryImp.swift
  WalWal/DependencyFactory/Feed/FeedDependencyFactory/Interface/FeedDependencyFactory.swift
  WalWal/DependencyFactory/MyPage/MyPageDependencyFactory/Implement/MyPageDependencyFactoryImp.swift
  WalWal/DependencyFactory/MyPage/MyPageDependencyFactory/Interface/MyPageDependencyFactory.swift
  WalWal/DesignSystem/Sources/WalWalFeed/WalWalFeed.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Reactors/CommentReactorImp.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/CommentViewImp.swift
  WalWal/Features/Comment/CommentPresenter/Interface/Reactors/CommentReactor.swift
  WalWal/Features/Comment/CommentPresenter/Project.swift
  WalWal/Features/Feed/FeedData/Implement/Endpoint/FeedEndpoint.swift
  WalWal/Features/Feed/FeedData/Implement/Repository/FeedRepositoryImp.swift
  WalWal/Features/Feed/FeedData/Interface/Repository/FeedRepository.swift
  WalWal/Features/Feed/FeedDomain/Implement/FetchSingleFeedUseCaseImp.swift
  WalWal/Features/Feed/FeedDomain/Interface/FetchSingleFeedUseCase.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/FeedViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/FeedReactor.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/RecordDetailReactorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Views/RecordDetailViewImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Interface/Reactors/RecordDetailReactor.swift
  WalWal/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
Labels: HotFix

#296 댓글 UX 개선
  WalWal/Coordinators/Feed/FeedCoordinator/Implement/FeedCoordinatorImp.swift
  WalWal/Coordinators/Feed/FeedCoordinator/Interface/FeedCoordinator.swift
  WalWal/DependencyFactory/Comment/CommentDependencyFactory/Implement/CommentDependencyFactoryImp.swift
  WalWal/DependencyFactory/Comment/CommentDependencyFactory/Interface/CommentDependencyFactory.swift
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCellView.swift
  WalWal/DesignSystem/Sources/WalWalFeed/WalWalFeed.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Reactors/CommentReactorImp.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/Cells/CommentCell.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/Cells/ReplyCommentCell.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/CommentViewImp.swift
  WalWal/Features/Comment/CommentPresenter/Interface/Reactors/CommentReactor.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/FeedViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/FeedReactor.swift
Labels: HotFix

#301 댓글 오류 수정
  WalWal/DesignSystem/Sources/CustomInputBox/CustomInputBox.swift
  WalWal/DesignSystem/Sources/CustomTextView/CustomTextView.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/CommentViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/FeedViewImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Views/RecordDetailViewImp.swift
Labels: HotFix

#302 미션 완료 카드 이미지 정상화
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/Cell/RecordCarouselCell.swift
Labels: HotFix

#303 알림 탭 - 피드 화면이동 구현
  WalWal/Coordinators/WalWalTabBar/WalWalTabBarCoordinator/Implement/WalWalTabBarCoordinatorImp.swift
  WalWal/Features/FCM/FCMDomain/Implement/SaveFeedRecordIDUseCaseImp.swift
  WalWal/Features/FCM/FCMDomain/Interface/Model/FCMTypes.swift
  WalWal/Features/FCM/FCMDomain/Interface/SaveFeedRecordIDUseCase.swift
  WalWal/Features/FCM/FCMPresenter/Implement/Reactors/FCMReactorImp.swift
  WalWal/Features/FCM/FCMPresenter/Implement/Views/Components/FCMCollectionViewCell.swift
  WalWal/Features/Feed/FeedDomain/Implement/RemoveGlobalRecordIdUseCaseImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/FeedViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/FeedReactor.swift
  WalWal/GlobalState/Sources/GlobalState.swift
  WalWal/ResourceKit/Resources/Images.xcassets/Notification/commentNoti.imageset/Contents.json
  WalWal/ResourceKit/Resources/Images.xcassets/Notification/commentNoti.imageset/comment.png
  WalWal/ResourceKit/Resources/Images.xcassets/Notification/commentNoti.imageset/comment@2x.png
  WalWal/ResourceKit/Resources/Images.xcassets/Notification/commentNoti.imageset/comment@3x.png
Labels: 구현

#306 탭바 아이템 선택 시 최상단 이동
  WalWal/Features/FCM/FCMPresenter/Implement/Reactors/FCMReactorImp.swift
  WalWal/Features/FCM/FCMPresenter/Implement/Views/FCMViewImp.swift
  WalWal/Features/FCM/FCMPresenter/Interface/Reactors/FCMReactor.swift
  WalWal/Features/Feed/FeedData/Implement/Endpoint/FeedEndpoint.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/FeedViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/FeedReactor.swift
Labels: 리팩토링

#307 댓글 알림 딥링크 처리
  WalWal/Coordinators/Comment/CommentCoordinator/Implement/CommentCoordinatorImp.swift
  WalWal/Coordinators/Feed/FeedCoordinator/Implement/FeedCoordinatorImp.swift
  WalWal/Coordinators/Feed/FeedCoordinator/Interface/FeedCoordinator.swift
  WalWal/Coordinators/MyPage/MyPageCoordinator/Implement/MyPageCoordinatorImp.swift
  WalWal/Coordinators/WalWalTabBar/WalWalTabBarCoordinator/Implement/WalWalTabBarCoordinatorImp.swift
  WalWal/DependencyFactory/Comment/CommentDependencyFactory/Implement/CommentDependencyFactoryImp.swift
  WalWal/DependencyFactory/Comment/CommentDependencyFactory/Interface/CommentDependencyFactory.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Reactors/CommentReactorImp.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/Cells/CommentCell.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/Cells/ReplyCommentCell.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/CommentViewImp.swift
  WalWal/Features/Comment/CommentPresenter/Interface/Reactors/CommentReactor.swift
  WalWal/Features/FCM/FCMData/Interface/DTO/FCMListDTO.swift
  WalWal/Features/FCM/FCMDomain/Implement/SaveFCMListGlobalStateUseCaseImp.swift
  WalWal/Features/FCM/FCMDomain/Implement/SaveFeedRecordIDUseCaseImp.swift
  WalWal/Features/FCM/FCMDomain/Interface/Model/FCMListModel.swift
  WalWal/Features/FCM/FCMDomain/Interface/SaveFeedRecordIDUseCase.swift
  WalWal/Features/FCM/FCMPresenter/Implement/Reactors/FCMReactorImp.swift
  WalWal/Features/FCM/FCMPresenter/Implement/Views/FCMViewImp.swift
  WalWal/Features/FCM/FCMPresenter/Interface/Reactors/FCMReactor.swift
  WalWal/Features/Feed/FeedDomain/Implement/RemoveGlobalRecordIdUseCaseImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
  WalWal/Features/Feed/FeedPresenter/Interface/Reactors/FeedReactor.swift
  WalWal/GlobalState/Sources/GlobalModels/GlobalFCMListModel.swift
  WalWal/GlobalState/Sources/GlobalState.swift
Labels: 구현

#308 온보딩 2차 QA 적용
  WalWal/DesignSystem/Sources/WalWalInputBox/WalWalInputBox.swift
  WalWal/Features/Onboarding/OnboardingPresenter/Implement/Views/Custom/DescriptionCell.swift
  WalWal/Features/Onboarding/OnboardingPresenter/Implement/Views/Custom/PermissionView.swift
  WalWal/Features/Onboarding/OnboardingPresenter/Implement/Views/Custom/PetView.swift
  WalWal/Features/Onboarding/OnboardingPresenter/Implement/Views/OnboardingProfileViewImp.swift
  WalWal/Features/Onboarding/OnboardingPresenter/Implement/Views/OnboardingSelectViewImp.swift
  WalWal/Features/Onboarding/OnboardingPresenter/Implement/Views/OnboardingViewImp.swift
  WalWal/ResourceKit/Resources/Assets.xcassets/OnboardingAssets/Onboarding1.imageset/Contents.json
  WalWal/ResourceKit/Resources/Assets.xcassets/OnboardingAssets/Onboarding1.imageset/img.png
  WalWal/ResourceKit/Resources/Assets.xcassets/OnboardingAssets/Onboarding1.imageset/img@2x.png
  WalWal/ResourceKit/Resources/Assets.xcassets/OnboardingAssets/Onboarding1.imageset/img@3x.png
  WalWal/ResourceKit/Resources/Assets.xcassets/OnboardingAssets/Onboarding1.imageset/onboarding1.png
  WalWal/ResourceKit/Resources/Assets.xcassets/OnboardingAssets/Onboarding1.imageset/onboarding1@2x.png
  WalWal/ResourceKit/Resources/Assets.xcassets/OnboardingAssets/Onboarding1.imageset/onboarding1@3x.png
  WalWal/ResourceKit/Resources/Assets.xcassets/PetType/CatIcon.imageset/cat.png
  WalWal/ResourceKit/Resources/Assets.xcassets/PetType/CatIcon.imageset/cat@2x.png
  WalWal/ResourceKit/Resources/Assets.xcassets/PetType/CatIcon.imageset/cat@3x.png
Labels: QA

#310 신고하기 QA 적용
  WalWal/DesignSystem/Sources/WalWalAlert/WalWalAlert.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/ReportView/ReportDetailViewImp.swift
  WalWal/Features/Feed/FeedPresenter/Implement/Views/ReportView/ReportTypeViewImp.swift
Labels: QA

#311 마이페이지 프로필 조회 오류 수정
  WalWal/Features/MyPage/MyPageDomain/Interface/Model/MemberModel.swift
Labels: HotFix

#313 미션 완료 뷰 QA 반영
  WalWal/DesignSystem/Sources/WalWalButton/WalWalButton_Icon/WalWalButton_Icon.swift
  WalWal/DesignSystem/Sources/WalWalTabBarViewController/WalWalTabBarViewController.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/BubbleView.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/Cell/RecordCarouselCell.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/MissionCompleteView.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
Labels: QA

#315 댓글 페이지 디자인 QA
  WalWal/DesignSystem/Sources/CustomInputBox/CustomInputBox.swift
  WalWal/DesignSystem/Sources/WalWalFeed/WalWalFeed.swift
  WalWal/Features/Comment/CommentData/Interface/DTO/GetCommentsDTO.swift
  WalWal/Features/Comment/CommentDomain/Interface/Model/FlattenCommentModel.swift
  WalWal/Features/Comment/CommentDomain/Interface/Model/GetCommentsModel.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/Cells/CommentCell.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/Cells/ReplyCommentCell.swift
  WalWal/Features/Comment/CommentPresenter/Implement/Views/CommentViewImp.swift
  WalWal/ResourceKit/Resources/Colors.xcassets/Opacity/Black70.colorset/Contents.json
  WalWal/ResourceKit/Sources/Font.swift
Labels: QA

#316 미션 기록 시 이모지 입력 시 오류 수정
  WalWal/DesignSystem/Sources/UnderlinedTextView/UnderlinedTextView.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/Cell/RecordCarouselCell.swift
  WalWal/Features/MissionUpload/MissionUploadPresenter/Implement/Views/Component/StyledTextInputView.swift
Labels: HotFix

#325 신고하기 endpoint 변경
  WalWal/Features/Feed/FeedData/Implement/Endpoint/FeedEndpoint.swift
Labels: HotFix

#319 앱 진입 시 푸시 권한 체크
  WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
  WalWal/Features/Mission/MissionPresenter/Interface/Reactors/MissionReactor.swift
  WalWal/Utility/Sources/PermissionManager.swift
Labels: HotFix

#334 프로필 조회 오류 수정
  WalWal/Features/MyPage/MyPagePresenter/Implement/Views/MyPageViewImp.swift
  WalWal/GlobalState/Sources/GlobalState.swift
Labels: HotFix

#333 인디케이터 및 피드( 기록 ) QA 적용
  WalWal/DesignSystem/Sources/WalWalFeed/Component/FeedHeaderView.swift
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCellView.swift
  WalWal/DesignSystem/Sources/WalWalFeed/WalWalFeed.swift
  WalWal/DesignSystem/Sources/WalWalLoadingIndicator/WalWalRefreshControl.swift
  WalWal/Features/FCM/FCMPresenter/Implement/Views/FCMViewImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/RecordDetailReactorImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Implement/Views/RecordDetailViewImp.swift
  WalWal/Features/MyPage/MyPagePresenter/Interface/Reactors/RecordDetailReactor.swift
Labels: QA

#335 SNS 정책 권한 추가 및 권한 요청 추가
  WalWal/DesignSystem/Sources/PermissionAlert/PermissionView.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
  WalWal/Features/Mission/MissionPresenter/Interface/Reactors/MissionReactor.swift
  WalWal/Features/Onboarding/OnboardingPresenter/Implement/Views/OnboardingSelectViewImp.swift
  WalWal/LocalStorage/Sources/UserDefaults.swift
  WalWal/ResourceKit/Resources/Images.xcassets/Large/Comment_L.imageset/Comment.png
  WalWal/ResourceKit/Resources/Images.xcassets/Large/Comment_L.imageset/Comment@2x.png
  WalWal/ResourceKit/Resources/Images.xcassets/Large/Comment_L.imageset/Comment@3x.png
  WalWal/ResourceKit/Resources/Images.xcassets/Large/Comment_L.imageset/Contents.json
  WalWal/ResourceKit/Resources/Images.xcassets/Small/Comment_S.imageset/Comment.png
  WalWal/ResourceKit/Resources/Images.xcassets/Small/Comment_S.imageset/Comment@2x.png
  WalWal/ResourceKit/Resources/Images.xcassets/Small/Comment_S.imageset/Comment@3x.png
  WalWal/ResourceKit/Resources/Images.xcassets/Small/Comment_S.imageset/Contents.json
  WalWal/ResourceKit/Sources/LegalText.swift
  WalWal/Utility/Sources/PermissionManager.swift
Labels: 구현

#338 미션 완료 뷰 디자인 QA
  WalWal/DesignSystem/Sources/WalWalButton/WalWalButton_Icon/WalWalButton_Icon.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/Cell/RecordCarouselCell.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/MissionCompleteView.swift
  WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
Labels: QA

#339 온보딩 레이아웃 수정
  WalWal/Features/Onboarding/OnboardingPresenter/Implement/Views/OnboardingProfileViewImp.swift
  WalWal/Features/Onboarding/OnboardingPresenter/Implement/Views/OnboardingSelectViewImp.swift
Labels: HotFix

#340 tabbar qa내용 적용
  WalWal/DesignSystem/Sources/WalWalTabBarViewController/Component/TabBarItemView.swift
  WalWal/DesignSystem/Sources/WalWalTabBarViewController/Component/WalWalTabBarView.swift
Labels: QA

#346 프로필 이미지 레이아웃 수정
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCellView.swift
Labels: HotFix

#347 부스트 시 프로필 모양 오류 수정
  WalWal/DesignSystem/Sources/WalWalFeed/Component/WalWalFeedCellView.swift
Labels: HotFix

#349 미션 완료 뷰 에러 해결
  WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/Cell/RecordCarouselCell.swift
Labels: HotFix
